Adding wordpress tweaks

diff --git a/scripts/restore-snapshot b/scripts/restore-snapshot
--- a/scripts/restore-snapshot
+++ b/scripts/restore-snapshot
@@ -21,8 +21,22 @@ function report() {
 
 function execute() {
   cmd="$1"
-  [ ! -z "$verbose" ] && echo "$cmd"
-  [ -z "$dry_run" ] && eval "$cmd"
+  [ ! -z "$verbose" ] && echo -n "$cmd..."
+  if [ -z "$dry_run" ]
+  then
+    eval "$cmd"
+    result=$?
+    if [ $result -eq 0 ]
+    then
+      [ ! -z "$verbose" ] && echo "($result)"
+    else
+      echo -n "Command failed ($result)"
+      [ -z "$verbose" ] && echo -n "\"$cmd\""
+      echo ""
+    fi
+  else
+    echo ""
+  fi
 }
   
 ###############################
@@ -48,6 +62,7 @@ require_apache_stopped
 site_files="$src/site-files.tar.gz"
 db_data="$src/$db.sql"
 config="$src/wp-config.php"
+session="$src/session.php"
 
 [ ! -e "$site_files" ] && echo "Cannot find website tarball \"$site_files\". Exiting now." && exit
 [ ! -e "$db_data" ] && echo "Cannot find db data \"$db_data\". Exiting now." && exit
@@ -79,3 +94,4 @@ execute "cd $(dirname $web)"
 execute "rm -rf $(basename $web)"
 execute "tar -xzf $site_files"
 execute "cp $config $(basename $web)"
+[ -e "$session" ] && execute "cp $session $(basename $web)/wp-includes"
