scripts and notes

diff --git a/scripts/restore-snapshot b/scripts/restore-snapshot
--- a/scripts/restore-snapshot
+++ b/scripts/restore-snapshot
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 function usage() {
-  echo "Usage: restore-snapshot -s <src> -d <db-name> -w <web-path> [ -x dry ] [ -v verbose ]"
+  echo "Usage: restore-snapshot [ -d <db-file[:name]> ] [ -w <web-site[:branch[:name]]> ] [ -x dry ] [ -v verbose ]"
 }
 
 function database_exists() {
@@ -15,15 +15,31 @@ function require_apache_stopped() {
   [ ! -z "$status" ] && echo "Cannot restore a website with apache status \"$status\"" && exit
 }
 
+function require_branch() {
+  repo=$1
+  branch=$2
+  pushd $repo &> /dev/null
+  git rev-parse --verify $branch &> /dev/null
+  [ $? -ne 0 ] && echo "Cannot find branch $branch in repository $repo. Exiting now." && exit
+}
+
+function get_current_branch() {
+  repo=$1
+  pushd $repo &> /dev/null
+  branch="$(git branch 2> /dev/null | grep "\*" | cut -d ' ' -f 2)"
+  echo $branch
+}
+
 function report() {
   [ ! -z "$verbose" ] && echo "$1"
 }
 
 function execute() {
   cmd="$1"
-  [ ! -z "$verbose" ] && echo -n "$cmd..."
+  [ ! -z "$verbose" ] && echo -n "$cmd"
   if [ -z "$dry_run" ]
   then
+    echo -n " ... "
     eval "$cmd"
     result=$?
     if [ $result -eq 0 ]
@@ -41,33 +57,66 @@ function execute() {
   
 ###############################
 
-while getopts "d:w:s:xv" option
+while getopts "d:w:xv" option
 do
   case $option in
     d) db=$OPTARG;;
-    s) src=$OPTARG;;
     w) web=$OPTARG;;
     x) verbose=true; dry_run=true;;
     v) verbose=true;
   esac
 done
 
-web_base=$(dirname $web)
+if [ ! -z "$web" ]
+then
+  if [[ "$web" == *:* ]]
+  then
+    web_repo=${web%%:*}
+    web_branch=${web#*:}
+    if [[ "$web_branch" == *:* ]]
+    then
+      web_name=${web_branch#*:}
+      web_branch=${web_branch%:*}
+    fi
+  else
+    web_repo=$web
+    web_branch="master"
+  fi
+  [ -z "$web_name" ] && web_name=$(basename $web_repo)
+  require_branch $web_repo $web_branch
 
-[ -z "$src" ] || [ -z "$db" ] || [ -z "$web" ] && usage && exit
-[ ! -e "$src" ] && echo "Cannot find source directory \"$src\". Exiting now." && exit
-[ ! -e "$web_base" ] && echo "Cannot find web directory \"$web_base\". Exiting now." && exit
-[ -z "$(which mysql)" ] && echo "Cannot find mysql. Exiting now." && exit
+  [ ! -d "$web_repo" ] && echo "Cannot find website repository $web_repo" && exit
+  [ $web_branch == $(get_current_branch $web_repo) ] && web_use_tree=true
+  web_base="/hd/www/html"
+  todo=true
+fi
+
+if [ ! -z "$db" ]
+then
+  if [[ $db == *:* ]]
+  then
+    db_data=${db%:*}
+    db_name=${db#*:}
+  else
+    db_data="$db"
+    db_name=$(basename $db)
+    db_name=${db_name%.sql}
+  fi
+  [[ ! -z "$db" && ! -e "$db_data" ]] && echo "Cannot find db data \"$db_data\". Exiting now." && exit
+  [ -z "$(which mysql)" ] && echo "Cannot find mysql. Exiting now." && exit
+  todo=true
+fi
+
+[ -z "$todo" ] && usage && exit
 require_apache_stopped
-site_files="$src/site-files.tar.gz"
-db_data="$src/$db.sql"
-config="$src/wp-config.php"
-session="$src/session.php"
 
-[ ! -e "$site_files" ] && echo "Cannot find website tarball \"$site_files\". Exiting now." && exit
-[ ! -e "$db_data" ] && echo "Cannot find db data \"$db_data\". Exiting now." && exit
-
-echo -e "Restoring:\n\tsource:   $src\n\tweb path: $web\n\tdatabase: $db"
+echo -e "Restoring:"
+if [ ! -z "$web" ]
+then
+  [ ! -z "$web_use_tree" ] && current_mark="*"
+  echo -e "\tweb repo $web_repo (branch $current_mark$web_branch) to site $web_name"
+fi
+[ ! -z "$db" ] && echo -e "\tdatabase: $db_name (from $db_data)"
 
 while (true)
 do
@@ -84,14 +133,23 @@ do
   fi
 done
 
-echo "Restoring database..."
-[ ! -z "$(database_exists $db)" ] && execute "mysql -u root -e \"drop database $db;\""
-execute "mysql -u root -e \"create database $db;\""
-execute "mysql $db < $db_data"
+if [ ! -z "$db" ]
+then
+  echo "Restoring database..."
+  [ ! -z "$(database_exists $db_name)" ] && execute "mysql -u root -e \"drop database $db_name;\""
+  execute "mysql -u root -e \"create database $db_name;\""
+  execute "mysql $db_name < $db_data"
+fi
 
-echo "Restoring website sources..."
-execute "cd $(dirname $web)"
-execute "rm -rf $(basename $web)"
-execute "tar -xzf $site_files"
-execute "cp $config $(basename $web)"
-[ -e "$session" ] && execute "cp $session $(basename $web)/wp-includes"
+if [ ! -z "$web" ]
+then
+  echo "Restoring website sources..."
+  execute "rm -rf $web_base/$web_name"
+  if [ ! -z "$web_use_tree" ]
+  then
+    execute "cp -R $web_repo $web_base"
+  else
+    execute "cd $web_repo &> /dev/null"
+    execute "git archive --format=tar $branch | tar -x -C $web_base/$web_name"
+  fi
+fi
